#!/usr/bin/env ruby

require 'cgi'
require 'erb'

cgi = CGI.new

printf "Content-type: text/html\r\n"
printf "\r\n"

template = "
<p>
  Parameters are:
</p>
<pre>
  <%= cgi.params.inspect  %>
</pre>
<p>
  Environment is:
</p>
<pre>
  <%= ENV.inspect.gsub(', ', \"\\n\")  %>
</pre>
"

begin
  p = File.dirname(__FILE__) + "/../templates"
  File.open("#{p}/sample.rhtml") {|f| template = f.read }

  ERB.new(template).run
rescue
  puts $!
end
